### ISSUE TITLE
Array 0 "txt" value isnt always the lyrics

### ISSUE THREAD

**Issue by elmills** [cgarwood/ProPresenter-vMix#5]
I am running on Windows (at least for testing) and ran into a strange issues where the "txt" value of array object 0 would at times be the current time.  Not sure if it is a function of the way we are setup, windows, etc but had to add the following code to the If statement to ensure we are only getting the current slide value. 

`&& message['ary'][0]['acn'] == 'cs' `

See the object array that I worked through to find the settings below.  Not sure that this should be incorporated into the code, but might help someone else if they have issues.
![2017-06-24 16_59_42-index html](https://user-images.githubusercontent.com/9019827/27518826-78a72f12-59b6-11e7-8d52-69e3645fbbe9.png)

**Comment by cgarwood** [comment]
fixed in 19c888efaa36643b58cd64e0686332fb85214e3d
